// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuringMachinesAPI.DataSources;

#nullable disable

namespace TuringMachinesAPI.Migrations
{
    [DbContext(typeof(TuringMachinesDbContext))]
    [Migration("20260113113716_Reports")]
    partial class Reports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuringMachinesAPI.Entities.AdminLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DoneAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetEntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Discussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InitialPostId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnswerPostId")
                        .IsUnique();

                    b.HasIndex("AuthorId");

                    b.HasIndex("InitialPostId")
                        .IsUnique();

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.LeaderboardLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("WorkshopItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopItemId");

                    b.ToTable("LeaderboardLevels");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.LevelSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionCount")
                        .HasColumnType("integer");

                    b.Property<int>("LeaderboardLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LeaderboardLevelId");

                    b.HasIndex("PlayerId");

                    b.ToTable("LevelSubmissions");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.LevelWorkshopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlphabetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectExamplesJson")
                        .HasColumnType("text");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LevelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TransformTestsJson")
                        .HasColumnType("text");

                    b.Property<bool>("TwoTapes")
                        .HasColumnType("boolean");

                    b.Property<int>("WorkshopItemId")
                        .HasColumnType("integer");

                    b.Property<string>("WrongExamplesJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LevelWorkshopItems");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasStarted")
                        .HasColumnType("boolean");

                    b.Property<int>("HostPlayerId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("LobbyPlayers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("SelectedLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.MachineWorkshopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlphabetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkshopItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MachineWorkshopItems");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DiscussionId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PostId");

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportedItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportingUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportingUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.WorkshopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<int[]>("Subscribers")
                        .HasColumnType("integer[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("WorkshopItems");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.AdminLog", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Discussion", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.Post", "AnswerPost")
                        .WithOne()
                        .HasForeignKey("TuringMachinesAPI.Entities.Discussion", "AnswerPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuringMachinesAPI.Entities.Player", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuringMachinesAPI.Entities.Post", "InitialPost")
                        .WithOne()
                        .HasForeignKey("TuringMachinesAPI.Entities.Discussion", "InitialPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnswerPost");

                    b.Navigation("Author");

                    b.Navigation("InitialPost");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.LeaderboardLevel", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.WorkshopItem", null)
                        .WithMany()
                        .HasForeignKey("WorkshopItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.LevelSubmission", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.LeaderboardLevel", null)
                        .WithMany()
                        .HasForeignKey("LeaderboardLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuringMachinesAPI.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Post", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.Player", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuringMachinesAPI.Entities.Discussion", "Discussion")
                        .WithMany("Posts")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Discussion");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.PostVote", b =>
                {
                    b.HasOne("TuringMachinesAPI.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuringMachinesAPI.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TuringMachinesAPI.Entities.Discussion", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
